window.S3_TOPICS = [
  {
    id: "jm24",
    code: "JM24",
    lesson: 24,
    title: "Law of Indices",
    symbol: "aˣ",
    artClass: "art-indices",
    ready: true,
    desc: "Interactive tools for powers and binary, plus comics.",
    tags: ["Tools", "Comics", "Game"],
  },
  {
    id: "jm25",
    code: "JM25",
    lesson: 25,
    title: "More about Factorization and Polynomials",
    symbol: "(x+a)(x+b)",
    artClass: "art-factor",
    ready: true,
    desc: "Factorization walkthroughs, Bracket Labyrinth manga, and shooter game.",
    tags: ["Tools", "Comics", "Game"],
  },
  {
    id: "jm26",
    code: "JM26",
    lesson: 26,
    title: "Inequalities I",
    symbol: "≥",
    artClass: "art-ineq",
    ready: true,
    desc: "Classroom manga, quiz, and Boundary Runner game on inequalities.",
    tags: ["Comics", "Game"],
  },
  {
    id: "jm27",
    code: "JM27",
    lesson: 27,
    title: "Percentages II",
    symbol: "%",
    artClass: "art-pct",
    ready: false,
    desc: "Change factor, interest, and tax — coming soon.",
    tags: ["Coming soon"],
  },
  {
    id: "jm28",
    code: "JM28",
    lesson: 28,
    title: "Special Lines in Triangles",
    symbol: "△ABC",
    artClass: "art-triangle",
    ready: true,
    desc: "Classroom manga — special lines, four triangle centres, angle pairs, and similar and congruent triangles.",
    tags: ["Comics"],
  },
  {
    id: "jm29",
    code: "JM29",
    lesson: 29,
    title: "Quadrilaterals",
    symbol: "AB // CD",
    artClass: "art-quad",
    ready: false,
    desc: "Properties of quadrilaterals — coming soon.",
    tags: ["Coming soon"],
  },
  {
    id: "jm30",
    code: "JM30",
    lesson: 30,
    title: "Probabilities",
    symbol: "P(A)",
    artClass: "art-prob",
    ready: false,
    desc: "Formula, tree diagrams, and tabulation — coming soon.",
    tags: ["Coming soon"],
  },
  {
    id: "jm31",
    code: "JM31",
    lesson: 31,
    title: "Measures of Central Tendencies",
    symbol: "x̄",
    artClass: "art-stats",
    ready: false,
    desc: "Mean, median, and mode — coming soon.",
    tags: ["Coming soon"],
  },
  {
    id: "jm32",
    code: "JM32",
    lesson: 32,
    title: "Areas and Volumes III",
    symbol: "V = πr²h",
    artClass: "art-volume",
    ready: false,
    desc: "Surface area and volume — coming soon.",
    tags: ["Coming soon"],
  },
  {
    id: "jm33",
    code: "JM33",
    lesson: 33,
    title: "Coordinates of Straight Lines",
    symbol: "m₁m₂ = −1",
    artClass: "art-lines",
    ready: false,
    desc: "Slope, equations, and perpendicular lines — coming soon.",
    tags: ["Coming soon"],
  },
  {
    id: "jm34",
    code: "JM34",
    lesson: 34,
    title: "Trigonometric Relations",
    symbol: "sin²θ + cos²θ = 1",
    artClass: "art-trig",
    ready: false,
    desc: "Identities and trigonometric relations — coming soon.",
    tags: ["Coming soon"],
  },
  {
    id: "jm35",
    code: "JM35",
    lesson: 35,
    title: "Application of Trigonometry",
    symbol: "h = d tan θ",
    artClass: "art-trig-app",
    ready: false,
    desc: "Heights, distances, and bearings — coming soon.",
    tags: ["Coming soon"],
  },
];

window.getTopicById = function getTopicById(id) {
  return window.S3_TOPICS.find(function (t) {
    return t.id === id;
  });
};
