window.JM28_COMICS_QUIZ = {
  triangleLines: [
    {
      id: "tri-q1",
      questionEn: "In △ABC, which segment is the altitude from vertex A?",
      questionZh: "在 △ABC 中，邊個線段係由頂點 A 出發嘅高？",
      hintEn: "An altitude is perpendicular to the line containing the opposite side. Look for the right-angle mark at the foot.",
      hintZh: "高線垂直於含對邊嘅直線。搵垂足嘅直角符號。",
      choices: [
        { textEn: "AD, where D lies on BC and ∠ADB = 90°", textZh: "AD，D 在 BC 上且 ∠ADB = 90°", correct: true },
        { textEn: "AM, where M is the midpoint of BC", textZh: "AM，M 係 BC 嘅中點", correct: false },
        { textEn: "AE, which splits ∠A into two equal parts", textZh: "AE，把 ∠A 分成兩等份", correct: false },
        { textEn: "The line through the midpoint of BC at right angles to BC", textZh: "過 BC 中點且垂直 BC 嘅直線", correct: false },
      ],
    },
    {
      id: "tri-q2",
      questionEn: "In △PQR, which segment is the median from vertex Q?",
      questionZh: "在 △PQR 中，邊個線段係由頂點 Q 出發嘅中線？",
      hintEn: "A median joins a vertex to the midpoint of the opposite side.",
      hintZh: "中線連頂點同對邊中點。",
      choices: [
        { textEn: "QS, where S is the midpoint of PR", textZh: "QS，S 係 PR 嘅中點", correct: true },
        { textEn: "QT, where T lies on PR and ∠QTP = 90°", textZh: "QT，T 在 PR 上且 ∠QTP = 90°", correct: false },
        { textEn: "QU, which splits ∠Q into two equal parts", textZh: "QU，把 ∠Q 分成兩等份", correct: false },
        { textEn: "The line through the midpoint of PR at right angles to PR", textZh: "過 PR 中點且垂直 PR 嘅直線", correct: false },
      ],
    },
    {
      id: "tri-q3",
      questionEn: "In △ABC, M is the midpoint of side BC. Which line is the perpendicular bisector of BC?",
      questionZh: "在 △ABC 中，M 係邊 BC 嘅中點。邊條直線係 BC 嘅垂直平分線？",
      hintEn: "The line must pass through midpoint M and be perpendicular to BC.",
      hintZh: "條直線必須經過中點 M，而且垂直於 BC。",
      choices: [
        { textEn: "Line L passes through M, with L perpendicular to BC", textZh: "直線 L 經過 M，而且 L 垂直於 BC", correct: true },
        { textEn: "Segment AM from A to midpoint M", textZh: "由 A 連到中點 M 嘅線段 AM", correct: false },
        { textEn: "A line through B perpendicular to AC", textZh: "經過 B 且垂直於 AC 嘅直線", correct: false },
        { textEn: "A ray from A that splits ∠BAC equally", textZh: "由 A 出發並將 ∠BAC 平分嘅射線", correct: false },
      ],
    },
    {
      id: "tri-q4",
      questionEn: "In △ABC, ray AE starts at vertex A. Which information shows that AE is the angle bisector of ∠BAC?",
      questionZh: "在 △ABC 中，射線 AE 由頂點 A 出發。邊項資料表示 AE 係 ∠BAC 嘅角平分線？",
      hintEn: "An angle bisector divides one angle into two equal angles.",
      hintZh: "角平分線會將一個角分成兩個相等嘅角。",
      choices: [
        { textEn: "∠BAE = ∠EAC", textZh: "∠BAE = ∠EAC", correct: true },
        { textEn: "BE = EC", textZh: "BE = EC", correct: false },
        { textEn: "AE ⊥ BC", textZh: "AE ⊥ BC", correct: false },
        { textEn: "AB = AC", textZh: "AB = AC", correct: false },
      ],
    },
    {
      id: "tri-q5",
      questionEn: "The orthocentre of a triangle is the meeting point of which lines?",
      questionZh: "三角形嘅垂心係邊啲線嘅交點？",
      hintEn: "Look for the three altitudes.",
      hintZh: "搵三條高線。",
      choices: [
        { textEn: "The three altitudes", textZh: "三條高線", correct: true },
        { textEn: "The three medians", textZh: "三條中線", correct: false },
        { textEn: "The three internal angle bisectors", textZh: "三條內角平分線", correct: false },
        { textEn: "The three perpendicular bisectors of the sides", textZh: "三邊嘅垂直平分線", correct: false },
      ],
    },
    {
      id: "tri-q6",
      questionEn: "Where is the centroid of an obtuse triangle?",
      questionZh: "鈍角三角形嘅重心喺邊？",
      hintEn: "The centroid is the balance point. It stays inside every triangle.",
      hintZh: "重心係平衡點，任何三角形都喺內部。",
      choices: [
        { textEn: "Inside the triangle", textZh: "喺三角形內", correct: true },
        { textEn: "Outside the triangle", textZh: "喺三角形外", correct: false },
        { textEn: "On the longest side", textZh: "喺最長邊上", correct: false },
        { textEn: "At the obtuse vertex", textZh: "喺鈍角頂點", correct: false },
      ],
    },
    {
      id: "tri-q7",
      questionEn: "Which statement about the in-centre is true?",
      questionZh: "關於內心，邊句正確？",
      hintEn: "The in-centre is where the internal angle bisectors meet, and it is the centre of the incircle.",
      hintZh: "內心係內角平分線交點，亦係內切圓圓心。",
      choices: [
        { textEn: "It is the centre of the circle that touches all three sides, and it is inside both acute and obtuse triangles", textZh: "佢係與三邊相切嘅圓嘅圓心，銳角同鈍角三角形都喺內部", correct: true },
        { textEn: "It is outside an obtuse triangle", textZh: "鈍角三角形時佢喺外部", correct: false },
        { textEn: "It is the meeting point of the three medians", textZh: "佢係三條中線嘅交點", correct: false },
        { textEn: "It is the centre of the circle through all three vertices", textZh: "佢係通過三個頂點嘅圓嘅圓心", correct: false },
      ],
    },
    {
      id: "tri-q8",
      questionEn: "Where is the circumcentre of an obtuse triangle?",
      questionZh: "鈍角三角形嘅外心喺邊？",
      hintEn: "The circumcentre is where the perpendicular bisectors meet. In an obtuse triangle it lies outside.",
      hintZh: "外心係垂直平分線交點。鈍角三角形時喺外部。",
      choices: [
        { textEn: "Outside the triangle", textZh: "喺三角形外", correct: true },
        { textEn: "Inside the triangle", textZh: "喺三角形內", correct: false },
        { textEn: "At the obtuse vertex", textZh: "喺鈍角頂點", correct: false },
        { textEn: "At the midpoint of the shortest side", textZh: "喺最短邊嘅中點", correct: false },
      ],
    },
  ],
  anglePairs: [
    {
      id: "angle-q1",
      questionEn: "What is a transversal?",
      questionZh: "咩係截線（transversal）？",
      hintEn: "Look for one line that crosses the other two lines.",
      hintZh: "搵一條同時穿過另外兩條直線嘅線。",
      choices: [
        { textEn: "A line that crosses two or more other lines", textZh: "一條穿過兩條或以上直線嘅線", correct: true },
        { textEn: "A line that never meets another line", textZh: "一條永遠唔會同其他直線相交嘅線", correct: false },
        { textEn: "A line that bisects an angle", textZh: "一條平分角嘅線", correct: false },
        { textEn: "A line perpendicular to every line", textZh: "一條垂直於所有直線嘅線", correct: false },
      ],
    },
    {
      id: "angle-q2",
      questionEn: "Two parallel lines are cut by a transversal. Which description identifies corresponding angles?",
      questionZh: "兩條平行線被截線穿過。邊個描述係同位角？",
      hintEn: "Corresponding angles occupy the same corner at the two intersections.",
      hintZh: "同位角喺兩個交點佔相同角落位置。",
      choices: [
        { textEn: "They occupy the same relative corner at the two intersections", textZh: "佢哋喺兩個交點佔相同相對位置", correct: true },
        { textEn: "They are inside and on opposite sides of the transversal", textZh: "佢哋喺兩線之內、截線兩側", correct: false },
        { textEn: "They are inside and on the same side of the transversal", textZh: "佢哋喺兩線之內、截線同一側", correct: false },
        { textEn: "They must share the same vertex", textZh: "佢哋一定共用同一個頂點", correct: false },
      ],
    },
    {
      id: "angle-q3",
      questionEn: "A corresponding angle is 73°. What is the matching corresponding angle?",
      questionZh: "一個同位角係 73°，配對嘅同位角係幾多度？",
      hintEn: "Corresponding angles are equal when the lines are parallel.",
      hintZh: "平行線嘅同位角相等。",
      choices: [
        { textEn: "73°", textZh: "73°", correct: true },
        { textEn: "107°", textZh: "107°", correct: false },
        { textEn: "146°", textZh: "146°", correct: false },
        { textEn: "17°", textZh: "17°", correct: false },
      ],
    },
    {
      id: "angle-q4",
      questionEn: "Which description identifies alternate angles?",
      questionZh: "邊個描述係內錯角（alternate angles）？",
      hintEn: "Think of a Z-shape.",
      hintZh: "諗吓 Z 形。",
      choices: [
        { textEn: "Inside the parallel lines and on opposite sides of the transversal", textZh: "喺兩條平行線之內，而且位於截線兩側", correct: true },
        { textEn: "Outside the parallel lines and on the same side of the transversal", textZh: "喺兩條平行線之外，而且位於截線同一側", correct: false },
        { textEn: "At the same intersection only", textZh: "只喺同一個交點", correct: false },
        { textEn: "Inside the parallel lines and on the same side of the transversal", textZh: "喺兩條平行線之內，而且位於截線同一側", correct: false },
      ],
    },
    {
      id: "angle-q5",
      questionEn: "One alternate angle is 128°. What is the matching alternate angle?",
      questionZh: "一個內錯角係 128°，配對嘅內錯角係幾多度？",
      hintEn: "Alternate angles are equal when the lines are parallel.",
      hintZh: "平行線嘅內錯角相等。",
      choices: [
        { textEn: "128°", textZh: "128°", correct: true },
        { textEn: "52°", textZh: "52°", correct: false },
        { textEn: "64°", textZh: "64°", correct: false },
        { textEn: "180°", textZh: "180°", correct: false },
      ],
    },
    {
      id: "angle-q6",
      questionEn: "Two co-interior angles are x and 137°. Find x.",
      questionZh: "兩個同旁內角係 x 同 137°。求 x。",
      hintEn: "Co-interior angles add up to 180° when the lines are parallel.",
      hintZh: "平行線嘅同旁內角之和係 180°。",
      choices: [
        { textEn: "43°", textZh: "43°", correct: true },
        { textEn: "137°", textZh: "137°", correct: false },
        { textEn: "53°", textZh: "53°", correct: false },
        { textEn: "317°", textZh: "317°", correct: false },
      ],
    },
  ],
  similarCongruent: [
    {
      id: "simcon-q1",
      questionEn: "Triangle ABC is similar to triangle DEF. Which vertex corresponds to B?",
      questionZh: "三角形 ABC 相似於三角形 DEF。邊個頂點同 B 對應？",
      hintEn: "Match the vertices by their positions in the written order.",
      hintZh: "按書寫次序逐個配對頂點。",
      choices: [
        { textEn: "E", textZh: "E", correct: true },
        { textEn: "D", textZh: "D", correct: false },
        { textEn: "F", textZh: "F", correct: false },
        { textEn: "It cannot be determined", textZh: "無法判斷", correct: false },
      ],
    },
    {
      id: "simcon-q2",
      questionEn: "Two similar triangles have corresponding sides 4 cm and 10 cm. What is the scale factor from the first triangle to the second?",
      questionZh: "兩個相似三角形嘅對應邊係 4 cm 同 10 cm。由第一個三角形到第二個嘅比例因子係幾多？",
      hintEn: "Divide the second corresponding side by the first.",
      hintZh: "用第二個對應邊除以第一個。",
      choices: [
        { textEn: "2.5", textZh: "2.5", correct: true },
        { textEn: "0.4", textZh: "0.4", correct: false },
        { textEn: "6", textZh: "6", correct: false },
        { textEn: "14", textZh: "14", correct: false },
      ],
    },
    {
      id: "simcon-q3",
      questionEn: "Which information is enough to prove that two triangles are similar by AA?",
      questionZh: "邊項資料足以用 AA 證明兩個三角形相似？",
      hintEn: "AA needs two pairs of equal corresponding angles.",
      hintZh: "AA 需要兩對相等嘅對應角。",
      choices: [
        { textEn: "Two pairs of corresponding angles are equal", textZh: "兩對對應角相等", correct: true },
        { textEn: "One pair of sides is equal", textZh: "一對邊相等", correct: false },
        { textEn: "The triangles have the same perimeter", textZh: "兩個三角形周界相同", correct: false },
        { textEn: "One angle in each triangle is acute", textZh: "每個三角形都有一個銳角", correct: false },
      ],
    },
    {
      id: "simcon-q4",
      questionEn: "The side lengths are 3, 4, 5 and 6, 8, 10. Which similarity test applies?",
      questionZh: "兩個三角形邊長分別係 3、4、5 同 6、8、10。應用邊個相似判定？",
      hintEn: "All three side pairs have the same ratio.",
      hintZh: "三對邊都有相同比例。",
      choices: [
        { textEn: "SSS similarity", textZh: "SSS 相似判定", correct: true },
        { textEn: "AA similarity", textZh: "AA 相似判定", correct: false },
        { textEn: "RHS congruence", textZh: "RHS 全等判定", correct: false },
        { textEn: "SSA congruence", textZh: "SSA 全等判定", correct: false },
      ],
    },
    {
      id: "simcon-q5",
      questionEn: "Which statement is always true for congruent triangles?",
      questionZh: "邊句對全等三角形一定正確？",
      hintEn: "Congruent triangles have the same shape and the same size.",
      hintZh: "全等三角形形狀同大小都相同。",
      choices: [
        { textEn: "All corresponding sides and angles are equal", textZh: "所有對應邊同對應角都相等", correct: true },
        { textEn: "Their corresponding sides only need to be proportional", textZh: "對應邊只需要成比例", correct: false },
        { textEn: "Their scale factor can be any positive number", textZh: "比例因子可以係任何正數", correct: false },
        { textEn: "They must both be right triangles", textZh: "兩個都必須係直角三角形", correct: false },
      ],
    },
    {
      id: "simcon-q6",
      questionEn: "Two side pairs are equal and the included angle is equal. Which congruence test applies?",
      questionZh: "兩對邊相等，而且夾角相等。應用邊個全等判定？",
      hintEn: "The equal angle lies between the two known sides.",
      hintZh: "相等角位於兩條已知邊之間。",
      choices: [
        { textEn: "SAS", textZh: "SAS", correct: true },
        { textEn: "SSS", textZh: "SSS", correct: false },
        { textEn: "AAS", textZh: "AAS", correct: false },
        { textEn: "SSA", textZh: "SSA", correct: false },
      ],
    },
    {
      id: "simcon-q7",
      questionEn: "Which set of information proves two right triangles congruent by RHS?",
      questionZh: "邊組資料可以用 RHS 證明兩個直角三角形全等？",
      hintEn: "RHS stands for right angle, hypotenuse and one corresponding side.",
      hintZh: "RHS 代表直角、斜邊同一對對應邊。",
      choices: [
        { textEn: "Equal right angles, equal hypotenuses and one equal corresponding side", textZh: "直角相等、斜邊相等，同一對對應邊相等", correct: true },
        { textEn: "Equal right angles only", textZh: "只有直角相等", correct: false },
        { textEn: "Equal hypotenuses only", textZh: "只有斜邊相等", correct: false },
        { textEn: "Two non-included sides and any angle", textZh: "兩條非夾邊同任何一個角", correct: false },
      ],
    },
    {
      id: "simcon-q8",
      questionEn: "Which statement correctly compares similar and congruent triangles?",
      questionZh: "邊句正確比較相似三角形同全等三角形？",
      hintEn: "Congruent triangles are similar with scale factor 1.",
      hintZh: "全等三角形係比例因子為 1 嘅相似三角形。",
      choices: [
        { textEn: "Every congruent pair is similar, but a similar pair need not be congruent", textZh: "每對全等三角形都相似，但相似三角形未必全等", correct: true },
        { textEn: "Every similar pair is congruent", textZh: "每對相似三角形都全等", correct: false },
        { textEn: "Congruent triangles can have different corresponding side lengths", textZh: "全等三角形嘅對應邊長可以唔同", correct: false },
        { textEn: "Similar triangles must have scale factor 1", textZh: "相似三角形嘅比例因子一定係 1", correct: false },
      ],
    },
  ],
};
